name: CI for Astro site

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    name: Setup and Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "latest"
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
        shell: bash
      - name: Cache npm modules
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Build site
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            dist
            node_modules
            .lycheeignore

  check:
    needs: setup-and-build
    runs-on: ubuntu-latest
    name: Run Checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Check astro for errors
        run: npm run check
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html'
          fail: true
          failIfEmpty: false
          workingDirectory: "./dist"

  format:
    needs: setup-and-build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Format Code
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: node_modules
      - name: Prettier write
        run: npm run format
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "fix: apply prettier formatting"
          branch: ${{ github.ref_name }}
          file_pattern: "."