name: CI for Astro site

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install Dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  format:
    needs: [install]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Format Code
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Prettier write
        run: npm run format
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'fix: apply prettier formatting'

  build:
    needs: [install, format]
    if: always() && needs.install.result == 'success' && (needs.format.result == 'success' || needs.format.result == 'skipped')
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Check astro for errors
        run: npm run check
      - name: Build site
        run: npm run build
      - name: Add .lycheeignore
        run: cp .lycheeignore ./dist/.lycheeignore
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html'
          fail: true
          failIfEmpty: false
          workingDirectory: './dist'
